package main

import (
	"github.com/GIT_USER_ID/GIT_REPO_ID/src/models"
	"gorm.io/gorm"
)

/*
マスターデータの作成
*/
func AddMasterData(db *gorm.DB) {
	// 作品タイトルの挿入
	db.Create(&models.TitleOfWork{Name: "機動戦士ガンダム"})
	db.Create(&models.TitleOfWork{Name: "機動戦士Zガンダム"})
	db.Create(&models.TitleOfWork{Name: "機動戦士ガンダムZZ"})
	db.Create(&models.TitleOfWork{Name: "機動戦士ガンダム 逆襲のシャア"})
	db.Create(&models.TitleOfWork{Name: "機動戦士ガンダムF91"})
	db.Create(&models.TitleOfWork{Name: "機動戦士Vガンダム"})
	db.Create(&models.TitleOfWork{Name: "機動武闘伝Gガンダム"})
	db.Create(&models.TitleOfWork{Name: "新機動戦記ガンダムW"})
	db.Create(&models.TitleOfWork{Name: "新機動戦記ガンダムW Endless Waltz"})
	db.Create(&models.TitleOfWork{Name: "機動新世紀ガンダムX"})
	db.Create(&models.TitleOfWork{Name: "∀ガンダム"})
	db.Create(&models.TitleOfWork{Name: "機動戦士ガンダムSEED"})
	db.Create(&models.TitleOfWork{Name: "機動戦士ガンダムSEED DESTINY"})
	db.Create(&models.TitleOfWork{Name: "機動戦士ガンダムSEED C.E.73 STARGAZER"})
	db.Create(&models.TitleOfWork{Name: "機動戦士ガンダム00"})
	db.Create(&models.TitleOfWork{Name: "劇場版 機動戦士ガンダム00 -A wakening of the Trailblazer-"})
	db.Create(&models.TitleOfWork{Name: "機動戦士ガンダムUC"})
	db.Create(&models.TitleOfWork{Name: "機動戦士ガンダムAGE"})
	db.Create(&models.TitleOfWork{Name: "ガンダム Gのレコンギスタ"})
	db.Create(&models.TitleOfWork{Name: "機動戦士ガンダム 鉄血のオルフェンズ"})
	db.Create(&models.TitleOfWork{Name: "機動戦士ガンダム0080 ポケットの中の戦争"})
	db.Create(&models.TitleOfWork{Name: "機動戦士ガンダム0083 STARDUST MEMORY"})
	db.Create(&models.TitleOfWork{Name: "機動戦士ガンダム 第08MS小隊"})
	db.Create(&models.TitleOfWork{Name: "機動戦士ガンダム MS IGLOO"})
	db.Create(&models.TitleOfWork{Name: "機動戦士ガンダム サンダーボルト"})
	db.Create(&models.TitleOfWork{Name: "機動戦士ガンダム外伝 THE BLUE DESTINY"})
	db.Create(&models.TitleOfWork{Name: "機動戦士ガンダム外伝 ミッシングリンク"})
	db.Create(&models.TitleOfWork{Name: "ガンダム・センチネル"})
	db.Create(&models.TitleOfWork{Name: "機動戦士ガンダム 逆襲のシャア ベルトーチカ・チルドレン"})
	db.Create(&models.TitleOfWork{Name: "機動戦士ガンダム 閃光のハサウェイ"})
	db.Create(&models.TitleOfWork{Name: "機動戦士クロスボーン・ガンダム"})
	db.Create(&models.TitleOfWork{Name: "機動戦士ガンダムSEED ASTRAY"})
	db.Create(&models.TitleOfWork{Name: "機動戦士ガンダム ヴァルプルギス"})
	db.Create(&models.TitleOfWork{Name: "ガンダムビルド ファイターズ"})
	db.Create(&models.TitleOfWork{Name: "ガンダムビルド ファイターズトライ"})
	db.Create(&models.TitleOfWork{Name: "ガンダムビルド ファイターズA-R"})
	db.Create(&models.TitleOfWork{Name: "ガンダムビルド ダイバーズ"})
	db.Create(&models.TitleOfWork{Name: "MSV"})
	db.Create(&models.TitleOfWork{Name: "機動戦士ガンダム00V"})
	db.Create(&models.TitleOfWork{Name: "ガンダムEXA"})
	db.Create(&models.TitleOfWork{Name: "SDガンダム外伝"})
	db.Create(&models.TitleOfWork{Name: "THE-LIFE-SIZED νGUNDAM STATUE"})
	db.Create(&models.TitleOfWork{Name: "機動戦士ガンダム N-EXTREME"})

	// パイロットの挿入
	db.Create(&models.Pilot{Name: "東方不敗マスター・アジア"})
	db.Create(&models.Pilot{Name: "デメジエール・ソンネン"})
	db.Create(&models.Pilot{Name: "レイン・ミカムラ"})
	db.Create(&models.Pilot{Name: "シャア・アズナブル"})
	db.Create(&models.Pilot{Name: "クワトロ・バジーナ"})
	db.Create(&models.Pilot{Name: "フル・フロンタル"})
	db.Create(&models.Pilot{Name: "ベルリ・ゼナム"})
	db.Create(&models.Pilot{Name: "フォント・ボー"})
	db.Create(&models.Pilot{Name: "アスラン・ザラ"})
	db.Create(&models.Pilot{Name: "張五飛"})
	db.Create(&models.Pilot{Name: "ダンテ・D・ワーズロード"})
	db.Create(&models.Pilot{Name: "ノリス・パッカード"})
	db.Create(&models.Pilot{Name: "ハリー・オード"})
	db.Create(&models.Pilot{Name: "ジェリド・メサ"})
	db.Create(&models.Pilot{Name: "叢雲劾"})
	db.Create(&models.Pilot{Name: "ジョニー・ライデン"})
	db.Create(&models.Pilot{Name: "コウサカ・ユウマ"})
	db.Create(&models.Pilot{Name: "バナージ・リンクス"})
	db.Create(&models.Pilot{Name: "エビハラ・チカゲ"})
	db.Create(&models.Pilot{Name: "ゾルタン・アッカネン"})
	db.Create(&models.Pilot{Name: "アセム・アスノ"})
	db.Create(&models.Pilot{Name: "ヨナ・バシュタ"})
	db.Create(&models.Pilot{Name: "カリス・ノーティラス"})
	db.Create(&models.Pilot{Name: "アナベル・ガトー"})
	db.Create(&models.Pilot{Name: "ヤザン・ゲーブル"})
	db.Create(&models.Pilot{Name: "チボデー・クロケット"})
	db.Create(&models.Pilot{Name: "クリム・ニック"})
	db.Create(&models.Pilot{Name: "アマギ・サイ"})
	db.Create(&models.Pilot{Name: "ラカン・ダカラン"})
	db.Create(&models.Pilot{Name: "ソル・リューネ・ランジュ＆セレーネ・マクグリフ"})
	db.Create(&models.Pilot{Name: "ガロード・ランティファ・アディール"})
	db.Create(&models.Pilot{Name: "イオリ・セイ&レイジ"})
	db.Create(&models.Pilot{Name: "ソーマ・ピーリス"})
	db.Create(&models.Pilot{Name: "アレルヤ・ハプティズム＆マリー・パーファシー"})
	db.Create(&models.Pilot{Name: "レオス・アロイ"})
	db.Create(&models.Pilot{Name: "エマ・シーン"})
	db.Create(&models.Pilot{Name: "トレーズ・クシュリナーダ"})
	db.Create(&models.Pilot{Name: "アンドリュー・バルトフェルド"})
	db.Create(&models.Pilot{Name: "ロウ・ギュール"})
	db.Create(&models.Pilot{Name: "スウェン・カル・バヤン"})
	db.Create(&models.Pilot{Name: "カトル・ラバーバ・ウィナー"})
	db.Create(&models.Pilot{Name: "チェーン・アギ"})
	db.Create(&models.Pilot{Name: "マリーダ・クルス"})
	db.Create(&models.Pilot{Name: "アンジェロ・ザウパー"})
	db.Create(&models.Pilot{Name: "ロンド・ミナ・サハク"})
	db.Create(&models.Pilot{Name: "ティエリア・アーデ"})
	db.Create(&models.Pilot{Name: "ゼハート・ガレット"})
	db.Create(&models.Pilot{Name: "ヒリング・ケア"})
	db.Create(&models.Pilot{Name: "コレン・ナンダー"})
	db.Create(&models.Pilot{Name: "三日月・オーガス"})
	db.Create(&models.Pilot{Name: "ダリル・ローレンツ"})
	db.Create(&models.Pilot{Name: "ネーナ・トリニティ"})
	db.Create(&models.Pilot{Name: "バルカ・ニル"})
	db.Create(&models.Pilot{Name: "ステラ・ルーシェ"})
	db.Create(&models.Pilot{Name: "プレア・レヴェリー"})
	db.Create(&models.Pilot{Name: "フラム・ナラ"})
	db.Create(&models.Pilot{Name: "ジュンコ・ジェンコ"})
	db.Create(&models.Pilot{Name: "ミカミ・リク"})
	db.Create(&models.Pilot{Name: "ミリアルド・ピースクラフト"})
	db.Create(&models.Pilot{Name: "ゼクス・マーキス"})
	db.Create(&models.Pilot{Name: "ギム・ギンガナム"})
	db.Create(&models.Pilot{Name: "ムウ・ラ・フラガ"})
	db.Create(&models.Pilot{Name: "ハマーン・カーン"})
	db.Create(&models.Pilot{Name: "ウッソ・エヴィン"})
	db.Create(&models.Pilot{Name: "ルナマリア・ホーク"})
	db.Create(&models.Pilot{Name: "マクギリス・ファリド"})
	db.Create(&models.Pilot{Name: "ヴィンセント・グライスナー"})
	db.Create(&models.Pilot{Name: "マフティー・ナビーユ・エリン"})
	db.Create(&models.Pilot{Name: "ディアッカ・エルスマン"})
	db.Create(&models.Pilot{Name: "マスク"})
	db.Create(&models.Pilot{Name: "ユウキ・タツヤ"})
	db.Create(&models.Pilot{Name: "三代目メイジン・カワグチ"})
	db.Create(&models.Pilot{Name: "ミハイル・カミンスキー"})
	db.Create(&models.Pilot{Name: "パプテマス・シロッコ"})
	db.Create(&models.Pilot{Name: "アイーダ・スルガン"})
	db.Create(&models.Pilot{Name: "シャニ・アンドラス"})
	db.Create(&models.Pilot{Name: "カガリ・ユラ・アスハ"})
	db.Create(&models.Pilot{Name: "シン・アスカ"})
	db.Create(&models.Pilot{Name: "ユウ・カジマ"})
	db.Create(&models.Pilot{Name: "デュオ・マックスウェル"})
	db.Create(&models.Pilot{Name: "ラウ・ル・クルーゼ"})
	db.Create(&models.Pilot{Name: "レイ・ザ・バレル"})
	db.Create(&models.Pilot{Name: "ドモン・カッシュ"})
	db.Create(&models.Pilot{Name: "イザーク・ジュール"})
	db.Create(&models.Pilot{Name: "リボンズ・アルマーク"})
	db.Create(&models.Pilot{Name: "フェルト・グレイス"})
	db.Create(&models.Pilot{Name: "ユリン・ルシェル(＆デシル・ガレット)"})
	db.Create(&models.Pilot{Name: "昭弘・アルトランド"})
	db.Create(&models.Pilot{Name: "ガロード・ラン"})
	db.Create(&models.Pilot{Name: "セシア・アウェア"})
	db.Create(&models.Pilot{Name: "マ・クベ"})
	db.Create(&models.Pilot{Name: "シーブック・アノー"})
	db.Create(&models.Pilot{Name: "キンケドゥ・ナウ"})
	db.Create(&models.Pilot{Name: "カミキ・セカイ"})
	db.Create(&models.Pilot{Name: "カミーユ・ビダン"})
	db.Create(&models.Pilot{Name: "ロンド・ギナ・サハク"})
	db.Create(&models.Pilot{Name: "フリット・アスノ"})
	db.Create(&models.Pilot{Name: "キャプテン・アッシュ"})
	db.Create(&models.Pilot{Name: "トロワ・バートン"})
	db.Create(&models.Pilot{Name: "シン・マツナガ"})
	db.Create(&models.Pilot{Name: "ミスター・ブシドー"})
	db.Create(&models.Pilot{Name: "グラハム・エーカー"})
	db.Create(&models.Pilot{Name: "イオ・フレミング"})
	db.Create(&models.Pilot{Name: "リカルド・フェリーニ"})
	db.Create(&models.Pilot{Name: "リディ・マーセナス"})
	db.Create(&models.Pilot{Name: "ゼラ・ギンス"})
	db.Create(&models.Pilot{Name: "ハイネ・ヴェステンフルス"})
	db.Create(&models.Pilot{Name: "アヤメ"})
	db.Create(&models.Pilot{Name: "クロエ・クローチェ"})
	db.Create(&models.Pilot{Name: "ククルス・ドアン"})
	db.Create(&models.Pilot{Name: "ロラン・セアック"})
	db.Create(&models.Pilot{Name: "ニコル・アマルフィ"})
	db.Create(&models.Pilot{Name: "ジャン・リュック・デュバル"})
	db.Create(&models.Pilot{Name: "マシロ・オークス"})
	db.Create(&models.Pilot{Name: "クリスチーナ・マッケンジー"})
	db.Create(&models.Pilot{Name: "ニムバス・シュターゼン"})
	db.Create(&models.Pilot{Name: "アレンビー・ビアズリー"})
	db.Create(&models.Pilot{Name: "シロー・アマダ"})
	db.Create(&models.Pilot{Name: "ラライヤ・アクバール&ノレド・ナグ"})
	db.Create(&models.Pilot{Name: "ヤサカ・マオ"})
	db.Create(&models.Pilot{Name: "アリー・アル・サーシェス"})
	db.Create(&models.Pilot{Name: "カイ・シデン"})
	db.Create(&models.Pilot{Name: "アムロ・レイ"})
	db.Create(&models.Pilot{Name: "アカハナ"})
	db.Create(&models.Pilot{Name: "キラ・ヤマト"})
	db.Create(&models.Pilot{Name: "カナード・パルス"})
	db.Create(&models.Pilot{Name: "マシュマー・セロ"})
	db.Create(&models.Pilot{Name: "ジャミル・ニート"})
	db.Create(&models.Pilot{Name: "コウ・ウラキ"})
	db.Create(&models.Pilot{Name: "シュバルツ・ブルーダー"})
	db.Create(&models.Pilot{Name: "エルピー・プル"})
	db.Create(&models.Pilot{Name: "プルツー"})
	db.Create(&models.Pilot{Name: "ホシノ・フミナ"})
	db.Create(&models.Pilot{Name: "シーマ・ガラハウ"})
	db.Create(&models.Pilot{Name: "ガエリオ・ボードウィン"})
	db.Create(&models.Pilot{Name: "ロックオン・ストラトス(ニール・ディランディ)"})
	db.Create(&models.Pilot{Name: "ロックオン・ストラトス(ライル・ディランディ)"})
	db.Create(&models.Pilot{Name: "レーン・エイム"})
	db.Create(&models.Pilot{Name: "ヒイロ・ユイ"})
	db.Create(&models.Pilot{Name: "刹那・F・セイエイ"})
	db.Create(&models.Pilot{Name: "クラックス・ドゥガチ"})
	db.Create(&models.Pilot{Name: "ソシエ・ハイム"})
	db.Create(&models.Pilot{Name: "ノルバ・シノ"})
	db.Create(&models.Pilot{Name: "シャギア・フロスト"})
	db.Create(&models.Pilot{Name: "ジュドー・アーシタ"})
	db.Create(&models.Pilot{Name: "ダグ・シュナイド"})
	db.Create(&models.Pilot{Name: "ザビーネ・シャル"})
	db.Create(&models.Pilot{Name: "サイ・サイシー"})
	db.Create(&models.Pilot{Name: "トビア・アロナクス"})
	db.Create(&models.Pilot{Name: "ギュネイ・ガス"})
	db.Create(&models.Pilot{Name: "キオ・アスノ"})
	db.Create(&models.Pilot{Name: "クロト・ブエル"})
	db.Create(&models.Pilot{Name: "アレルヤ・ハプティズム"})
	db.Create(&models.Pilot{Name: "カテジナ・ルース"})

	// コストの挿入
	db.Create(&models.AirframeCost{Cost: 3000})
	db.Create(&models.AirframeCost{Cost: 2500})
	db.Create(&models.AirframeCost{Cost: 2000})
	db.Create(&models.AirframeCost{Cost: 1500})

	//  覚醒タイプの挿入
	db.Create(&models.AwakenType{Name: "白い悪魔"})
	db.Create(&models.AwakenType{Name: "赤い彗星"})
	db.Create(&models.AwakenType{Name: "ジャンク屋"})
	db.Create(&models.AwakenType{Name: "明鏡止水"})
	db.Create(&models.AwakenType{Name: "ガンダムファイター"})
	db.Create(&models.AwakenType{Name: "ゼロシステム"})
	db.Create(&models.AwakenType{Name: "月光蝶"})
	db.Create(&models.AwakenType{Name: "SEED"})
	db.Create(&models.AwakenType{Name: "コーディネイター"})
	db.Create(&models.AwakenType{Name: "トランザム"})
	db.Create(&models.AwakenType{Name: "Xラウンダー"})
	db.Create(&models.AwakenType{Name: "阿頼耶識"})
	db.Create(&models.AwakenType{Name: "EXAM"})
	db.Create(&models.AwakenType{Name: "ALICE"})
	db.Create(&models.AwakenType{Name: "ガンプラ(格闘寄り)"})
	db.Create(&models.AwakenType{Name: "ガンプラ(バランス)"})
	db.Create(&models.AwakenType{Name: "ガンプラ(射撃寄り)"})
	db.Create(&models.AwakenType{Name: "宇宙海賊"})
	db.Create(&models.AwakenType{Name: "ラクロアの勇者"})
	db.Create(&models.AwakenType{Name: "Gダイバー"})
	db.Create(&models.AwakenType{Name: "格闘寄り汎用1"})
	db.Create(&models.AwakenType{Name: "格闘寄り汎用2"})
	db.Create(&models.AwakenType{Name: "格闘高補正汎用"})
	db.Create(&models.AwakenType{Name: "射撃寄り汎用1"})
	db.Create(&models.AwakenType{Name: "射撃寄り汎用2"})
	db.Create(&models.AwakenType{Name: "バランス汎用"})
}
